nuxt-modules/tailwindcss

README.md
Feels like it should be part of the readme. Took me a while to find where to add this.
=> chore(docs): add purgeCSS config object example to readme

lib/templates/tailwind.css
per https://tailwindcss.com/docs/controlling-file-size/ base and components should not be purged.  I found this out the hard way after spending 3h trying to figure out why my local dev env was rendering different css than prod :)
=> Per Tailwind's docs, base and components should not be purged.

README.md, example/nuxt.config.js, example/pages/index.vue, lib/module.js, lib/templates/tailwind.config.json
closes #62
---
It can often be useful to reference tailwind configuration values in runtime. For example to access some of your theme values when dynamically applying inline styles in a component.
If you need resolved tailwind config in runtime, you can enable `exposeConfig` option in `nuxt.config`:
```js
// nuxt.config.js
{
tailwindcss: {
exposeConfig: true
},
}
```
Then import where needed from `~tailwind.config`:
```js
// Import fully resolved config
import tailwindConfig from '~tailwind.config'
// Import only part which is required to allow tree-shaking
import { theme } from '~tailwind.config'
```
**NOTE:** Please be aware this adds **~19.5KB (~3.5KB)** to the client bundle size.
=> feat: `exposeConfig` to reference resolved config in javascript runtime

README.md, example/assets/css/tailwind.css, example/nuxt.config.js, example/tailwind.config.js, lib/module.js, lib/templates/tailwind.config.js, lib/templates/tailwind.css, package.json, test/config.test.js, test/fail.test.js, test/ok.test.js, yarn.lock
This feature is a breaking change since it removes `nuxt-purgecss` dependency and options.
=> feat: use tailwind v1.4 and use purge option

lib/files/tailwind.config.js, test/config.test.js
1. This PR adds support for purging JS-file based components by default (helpful for small components with render functions)
2. Furthermore, ts and js declarations are grouped together
=> chore: improve purge globs

lib/ui/pages/index.vue
boxClasses() already implements a border-2 class by default.
Some background as to why this change matters: 
I'm using @nuxtjs/html-validator (https://html-validator.nuxtjs.org/) in a project, and the package is also validating the ./_tailwind colors page, thus giving me a duplicated border-2 class error message on the copy-box div.
As a side question: Is there a way to possibly turn off the generation of the colors via this module?
=> fix: remove duplicated border-2 class from copy-box

lib/serverMiddleware/tailwindConfigViewer.js
It is better using CommonJS for module exports to avoid mixing esm/cjs syntaxes in node_modules
resolves #235
=> fix(middleware): use cjs syntax

docs/content/en/options.md
This PR updates tailwind `configPath` with nuxt `srcDir` usage documentation in /options page
Note: Original [fix provided](https://github.com/nuxt-community/tailwindcss-module/issues/114#issuecomment-698885369) by @Atinux, I'm just updating the documentation
Why?: Cause it took me 2 hours of debugging in the middle of the night to identify the issue
=> docs: Update configPath documentation

docs/content/3.options.md
Link to "Learn more about overwriting Tailwind config" is broken and should be fixed
=> Fix broken link for Tailwind config

docs/content/1.index.md
Hi there !
Since we updated this module to use the tailwind JIT native implementation we have to change the Tailwindcss' Documentation's link in the documentation 😄
=> docs: change jit link since tailwind-jit is now native to tailwindcss

docs/content/3.options.md
This PR is a revised version of the document added in (#290).
- Use `<d-alert>`.
- Moved information from `exposeConfig` to the `configPath` section.
=> docs: Fix configPath Information

src/index.ts
resolve [https://github.com/nuxt-community/tailwindcss-module/issues/107](https://github.com/nuxt-community/tailwindcss-module/issues/107)
Set the `cssPath:  false` to disable adding the CSS, then user can manually add the tailwind.css file in the nuxt.config.js CSS option.
```javascript
export default {
css: [
'@/assets/style/tailwind.css'
],
tailwindcss: {
cssPath: false
}
}
```
=> feat: set cssPath false to disable adding the CSS

src/tailwind.config.ts
=> fix: specify files to avoid rootDir watcher

docs/content/tailwind/1.config.md
Ran into a build error using the resolved config with a project today:
`Cannot find module '~tailwind.config' or its corresponding type declarations.`
After reading the [`exposeConfig` PR](https://github.com/nuxt-community/tailwindcss-module/pull/69) I realized it was a missing alias. I hope documenting this can help other people with the same issue.
=> docs: Add note about using resolved config with TypeScript

docs/content/examples/1.basic.md, docs/content/examples/2.dark-mode.md, docs/content/settings.json
Let's keep @adamwathan alive a little longer.
=> docs: fix brand to `Tailwind CSS`

docs/content/3.options.md
Viewer is set to true by default
=> docs: add missing viewer option

playground/nuxt.config.ts, src/module.ts
Resolved issue when upgrading this module from 4.2.0 to 5.0.0-3 in Nuxt2 project and the wrong import path in the nuxt config.
=> fix: import `tailwindcss/resolveConfig` with extension

src/module.ts, yarn.lock
We [now have](https://github.com/nuxt/framework/pull/2812) a top-level `postcss` key for nuxt 3 schema.
This PR changes that (+ upgrades local nuxt 3 + kit in this project) as well as adding `tailwindcss` & related postcss plugins to the _end_ of the config, which should help with issues like https://github.com/nuxt-community/tailwindcss-module/issues/433 in future (by allowing users to configure thing before tailwind is added).
In addition, we enable the new `tailwindcss/nesting` plugin which is now [the recommended way](https://tailwindcss.com/docs/using-with-preprocessors#nesting), which fully resolves https://github.com/nuxt-community/tailwindcss-module/issues/433.
=> fix: append to postcss options and use new nuxt 3 schema

package.json, playground/app.vue, src/module.ts, tsconfig.json, yarn.lock
Currently importing the resolved config from `#tailwind-config` throws an error using TypeScript since the config file is not being written. This PR adds `@types/tailwindcss` and writes a simple `.d.ts` to the `.nuxt` folder to provide config types.
Before
After
=> fix: add tailwindcss types

docs/content/2.setup.md
@deprecated — This is no longer needed in Nuxt 3 and Nuxt Bridge; all modules should be added to modules instead.
=> docs: changed deprecated buildModules to modules

src/module.ts
This change updates the way the `cssPath` option is resolved. Instead of `resolveAlias` it uses `resolvePath` This is the same mechanism used for the resolution of `configPath`. This allows module users to resolve a stylesheet provided by a dependency. In our case, we have a component library that includes a `tailwind.css` file that we would like to share between applications.
- The module playground demonstrates the default behavior works as expected and includes `runtime/tailwind.css`. 
- You can see the module resolve the CSS file from a dependency in the following sandbox where we load only Tailwind's base styles from the tawilwindcss package:
- https://codesandbox.io/s/gifted-worker-g3lk8j?file=/playground/nuxt.config.ts
You can see annotated results in the screenshot below:
=> feat: resolve `cssPath` with `resolvePath`

docs/content/2.tailwind/3.editor-support.md
There are a few things to keep in mind when using the official Tailwind Intellisense Extension for VSCode.
I added a guide on how to properly set up the extension to work with @nuxtjs/tailwindcss.
=> docs: add editor support section

docs/content/1.getting-started/2.options.md, playground/nuxt.config.ts, src/module.ts, src/utils.ts
Specifying injection position as a simple integer can be both confusing and fragile. It requires you to manually count CSS files, and it's easy to forget about it when changing CSS settings.
This PR adds support for human-readable injection positions, that can be specified as:
* Number, for backward-compatibility
* `'first'` and `'last'` string literals
* `{ after: 'existing-file.css' }` object
=> feat: support for more semantic injection positions

package.json, src/module.ts, yarn.lock
Tailwindcss types are now included in the core tailwind packge. Thus, separate types package is not needed.
`@types/tailwindcss` is also deprecated by tailwindlabs
=> fix: remove now-unneeded `@types/tailwindcss`

src/module.ts
=> fix(module): remove prefix for tailwind viewer route on nuxt 2

src/module.ts, test/basic.test.ts, test/configs.test.ts, test/fixture/basic/alt-tailwind.config.js, test/fixture/basic/ts-tailwind.config.ts
Resolves #515
This PR fixes a regression that broke the default config path loading. 
Additionally:
- it adds a warning message to users when a config module is loaded but fails
- supports loading .mjs configs
- properly types `configPath` (already is supported as an array)
=> fix: resolve config paths fully and warn on config errors

docs/content/1.getting-started/1.setup.md
Hi.
Reviewing docs:  I read it as a setup for Nuxt 3 Tailwind, however the nuxt.config refers to the old 'export default' vs. the new direction.  Thus, suggesting stacking code boxes, with reference to the versions to load, as a possible solution?
ALSO... on the 'home page' for this site, it has an impage of the terminal with instructions.  That is great, however I'd also caption that image with 'See here for next steps', with hyper link to the next page.  I missread the home page last time I visited this site as 'that is all I needed to do'... I am very much a bigginner, thus the mistake.
Love your work.  You guys rock.
Thanks.  Nick
=> docs: Update setup.md

docs/content/1.getting-started/1.setup.md
Mentioning the need of adding Tailwind directives to custom tailwind style files. If we create a custom file without adding that directives, it will not work and that part isn't mentioned or clear enough in the setup guide. And putting it there make it easy to copy/past during the setup :)
=> docs: Mentioning the need of adding Tailwind directives

package.json, src/module.ts, yarn.lock
PR addresses a breaking change introduced in `h3@0.8`, which yields a warning on the latest Nuxt edge:
=> feat!: update viewer dev middleware to be compatible with `h3@0.8`

docs/content/2.tailwind/3.editor-support.md, src/module.ts
Fixes #533.
The doc page https://tailwindcss.nuxtjs.org/tailwind/editor-support can probably further simplified by removing the whole discussion about different config options and only instruct devs to set the `configFile` option to the generated cjs file in the nuxt folder. What do you think?
=> feat: expose config as commonjs file

CHANGELOG.md, docs/content/1.getting-started/1.setup.md, docs/content/1.getting-started/2.options.md, docs/content/2.tailwind/1.config.md, docs/content/2.tailwind/3.editor-support.md, src/module.ts
Closes #549 
Also simplifies editor support section as proposed in #535.
=> docs: Improve documentation for tailwind config and allow tailwind.config.cjs

docs/content/1.getting-started/2.options.md, src/module.ts
resolve #543 
If use `cssPath: false` option, tailwindcss path is unknown so Vite HMR is not available.
=> feat: add option to set `cssPath` to `false`

playground/nuxt.config.ts
`defineNuxtConfig` is now auto-imported.
=> chore: remove `defineNuxtConfig` import

src/module.ts
Fixes an error in Nuxt [3.0.0-rc.13-27781123.265db50](https://www.npmjs.com/package/nuxt3/v/3.0.0-rc.13-27781123.265db50) and above caused by dropping schema normalisation for Nuxt 2 in https://github.com/nuxt/framework/pull/8487.
Thanks to @danielroe for the pointer!
=> fix: normalise undefined `nuxt.options.watch`

src/module.ts
=> fix(exposeConfig): named exports in mjs for tree-shaking

docs/content/1.getting-started/2.options.md, docs/content/2.tailwind/1.config.md, package.json, src/module.ts, test/basic.test.ts
While working on #582, I've also looked into how to create exports for nested properties in the large tailwind configuration, and these properties can be accessed using exports in camelCase. There have been use-cases (for me at least) where I need a small part of the configuration, such as `theme.screens` or `theme.colors.neutral` instead of all of `theme` (which is quite big), so I can just do
```ts
import { themeScreens, themeColorsNeutral } from '#tailwind-config'
```
and that should do it!
I believe this isn't a major requirement right now, and may need feedback as well (hence I'm also putting this as a draft PR).
Edit: see changes at this point through - https://github.com/nuxt-modules/tailwindcss/compare/main...ineshbose:nuxt-tailwindcss-module:ba8bf7e2f3e1d907e0ab7b1a29a03dfd6d0bcde …
=> feat(exposeConfig): nested properties

src/module.ts
Follows #592 that fixed support for overriding default config (such as `content`) using `defu`, but lacked typed configuration - this implementation would help in future customisations too.
=> chore(types): extending config type interface

src/module.ts
=> fix: nested props resolution

src/module.ts, test/basic.test.ts
This PR aims to squeeze out as many exports possible from the nested exports feature introduced in #583.
Behaviour before PR with default `exposeLevel: 2` for file `#tailwind-config/theme/flexBasis` (when `maxLevel` is hit and it is a terminating file):
```js
export default {
// all properties in one object
"96": "24rem",
"auto": "auto",
"px": "1px",
"0.5": "0.125rem",
"1.5": "0.375rem",
"2.5": "0.625rem",
"3.5": "0.875rem",
"1/2": "50%",
}
```
Behaviour after PR:
```js
// ...all possible exports
const _96 = "24rem"
const _auto = "auto"
const _px = "1px"
const _full = "100%"
// same variables, along with unsafe vars
const config = { "96": _96, "auto": _auto, "px": _px, "full": _full, "0.5": "0.125rem", "1.5": "0.375rem", "2.5": "0.625rem", "3.5": "0.875rem", "1/2": "50%",  }
export { …
```
=> feat(exposeConfig): maximize nested exports

docs/content/2.tailwind/1.config.md, src/module.ts
As `utils` are also auto-imported, it should be added to the default `content` path for the TailwindCSS module.
=> chore: add `utils` to default content path

package.json, pnpm-lock.yaml, src/module.ts
Fixes #650, resolves #649 
Tailwind 3.3 introduced ESM and TS support, meaning they changed the stubs as well. I believe [config.simple.js](https://github.com/tailwindlabs/tailwindcss/blob/master/stubs/config.simple.js) is the closest one to [simpleConfig.stub.js](https://github.com/tailwindlabs/tailwindcss/blob/v3.2.7/stubs/simpleConfig.stub.js). 
I have successfully built the dev playground and tested the code.
=> chore(deps): update to tailwind 3.3.0

src/module.ts
Fixed the viewer is not working on nuxt 2
=> fix viewer

docs/content/0.index.md, docs/content/1.getting-started/1.setup.md, docs/content/1.getting-started/2.options.md, docs/content/2.tailwind/1.config.md, docs/content/2.tailwind/2.viewer.md, docs/content/2.tailwind/3.editor-support.md, docs/content/3.examples/1.basic.md, docs/content/3.examples/2.dark-mode.md, docs/content/3.examples/3.nuxtlabs-ui.md, docs/content/3.examples/4.postcss-plugin.md, docs/content/3.examples/7.tailwind-icons.md
* Enhanced clarity and readability of the content across 11 documentation files.
* Corrected various grammar, syntax, and punctuation errors.
* Improved phrasing and use of terminology where required.
* Ensured consistency in language and style across the documents.
* Optimized sentence structure for better understanding.
=> docs: Improve language across multiple documentation files

package.json
when using ts with `"module": "nodenext" / "bundler"`, the `types` field is expected on `exports` in `package.json`.
=> fix: add types to package.json exports map

src/resolvers.ts
https://github.com/nuxt-modules/tailwindcss/pull/747#issue-1974519872
Discussion: this may be a breaking change from `6.9.0`, but not from `<=6.8.1`, but you can argue that this is equivalent to "undoing" the change because the functionality remains the same from 6.8.1 onwards.
=> fix!: exclude modules from content

src/resolvers.ts
Weirdly enough the default isn't always set. The default is actually equal to "is the pages directory not empty" but assuming undefined means true is fine in this case as its only used to add a glob.
I also noticed use of `nuxt.options.dir.modules` causes an error to be logged to console, but removing that would be a breaking change now.
```
[16:13:24]  ERROR  This module cannot be imported in the Vue part of your app. [importing nuxt/kit from modules/my-module.ts]
```
=> fix: allow nuxt.options.pages to be unset

src/resolvers.ts
In the latest version, building a Nuxt2 app fails because `options.imports` is not defined. This change allows imports to not be defined and instead falls back to the empty array.
=> fix: allow options.imports to not be set

src/resolvers.ts
In my Nuxt2 app, `nuxt.options.extensions` is `[ 'js', 'mjs' ]`. This causes `.vue` to be excluded from tailwind.
This fix ensures that vue is always added as an extension, but I'm not sure if it's the correct approach. Maybe the options returned by nuxt kit should include it or maybe there is something wrong with my nuxt config? This does slightly change the behavior in that it's no longer possible to exclude vue files from tailwind, but I don't think that's a popular use-case.
=> fix: always include vue extension in SFC content paths

src/module.ts, src/resolvers.ts, src/types.ts, src/viewer.ts
closes #706 
addresses #561 
~~(doesn't work for SSG yet)~~ nevermind, the playground has some issues on this, but let's ship and get feedback
=> chore: implement fixes on viewer and allow exporting

src/viewer.ts
fix the url protocol slash use ufo. from [commit](https://github.com/nuxt-modules/tailwindcss/commit/aa75b799dd67773e8f1cc110e33551eb68cb34c3).
=> chore: fix protocol slash on tailwind viewer logger

docs/app.config.ts, docs/content/1.getting-started/2.options.md, src/module.ts, src/runtime/utils/tw.ts, src/types.ts
> There are documentation changes missing in this PR. I want to know your opinion on this first before continuing the development.
More often than not, there are times when you may want to write Tailwind CSS classes within TypeScript strings. For example:
```vue
<script setup lang="ts">
const variant = ref('primary');
const variantClasses = {
primary: "bg-red-400",
secondary: "bg-green-400",
};
</script>
<template>
<button :class="variantClasses[variant]">Click me</button>
</template>
```
When doing so, you lose intellisense in VSCode through [TailwindCSS extension](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss). To overcome this problem, the extension team created a setting to allow for [custom class name completion …
=> feat: add util to write tw classes inside strings

package.json, pnpm-lock.yaml
This updates the tailwindcss dependency to `~3.4.0` so we can use the new features shown here: https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.4.0
=> chore: update tailwindcss dependency to 3.4

docs/content/1.getting-started/1.installation.md, docs/content/1.getting-started/2.configuration.md, docs/content/2.tailwind/1.config.md, docs/content/2.tailwind/2.viewer.md, docs/content/2.tailwind/3.editor-support.md, playground/nuxt.config.ts, playground/pages/index.vue, src/module.ts, src/resolvers.ts, src/runtime/utils.ts, src/runtime/utils/tw.ts, src/templates.ts, src/types.ts
This PR expands on providing editor support utilities as part of the module.
TODO:
=> feat: `editorSupport` option

docs/content/1.getting-started/2.configuration.md, package.json, playground/nuxt.config.ts, src/module.ts, src/resolvers.ts, src/types.ts, src/vite-hmr.ts
This should also make `injectPosition` more clear to be related to `cssPath` and not add to root-config.
Last config change I promise!
=> refactor: move `injectPosition` to `cssPath`

docs/content/2.tailwind/1.config.md
I noticed the missing `export default` in the JS file when copying it into my project.
=> docs: add export default to default config example

package.json, pnpm-lock.yaml, src/viewer.ts
https://github.com/unjs/consola/tree/v3.2.3?tab=readme-ov-file#console-utils
https://github.com/unjs/consola/blob/v3.2.3/src/utils/color.ts
=> refactor: move `colorette` to `consola/utils`

docs/content/1.getting-started/2.configuration.md
This pull request is intended to update the `configuration` page in the Nuxt Tailwind documentation with the latest configurations to get rid of the deprecation warnings shown below:
=> docs: update Nuxt Tailwind configuration docs

README.md, docs/content/1.getting-started/1.installation.md
This updates the documentation to use the [`nuxi module add` command](https://github.com/nuxt/cli/pull/197) which should simplify docs a bit and also improve user experience as there's no need to add to `nuxt.config` manually.
It's documented [here](https://nuxt.com/docs/api/commands/module#nuxi-module-add).
I may have missed a few spots in the documentation as I'm doing this across the modules ecosystem assisted by the power of regular expressions ✨, so I'd appreciate a review 🙏
=> docs: use new `nuxi module add` command in installation

src/module.ts
Fixed issue #883: `Cannot find any path matching /_tailwind/`, when using `baseUrl`: `/dev/`.
Additionally added conditional `baseURL` output, where if it matches `/` it prefixes empty string `''`, making final Tab view src always `/dev/_tailwind/` (depending on `nuxt.config.ts`) or `/_tailwind/`.
Issue #883
- [ x] 🐞 Bug fix (a non-breaking change that fixes an issue)
```
Fixed issue #883: Cannot find any path matching /_tailwind/, when using baseUrl: '/dev/'.
```
This change is required to fix _Tailwind Config Viewer_ embedded url by appending missing [`baseUrl`](https://nuxt.com/docs/api/nuxt-config#baseurl) setting (if set).
=>  fix: #883 Tab view src leading baseURL

package.json
With Nuxt 4 on the horizon, this updates the module compatibility definition to allow it to be installed on Nuxt v4. (Otherwise Nuxt will indicate the module might not be compatible.)
When Nuxt v4 comes out then you might decide or need to make breaking changes in this module and release a new major, but hopefully the migration should be smoother. 🙏 
👉 You can follow this and other changes in https://github.com/nuxt/nuxt/issues/27613 - please feel free to provide feedback as well!
=> chore: indicate compatibility with new v4 major

docs/content/2.tailwind/1.config.md, playground/app/spa-loading-template.html, playground/nuxt.config.ts, src/resolvers.ts
resolves #906
This simply adds `spa-loading-template.html` to the default content config and updates the docs accordingly
=> feat(content): add `spaLoadingTemplate` to content resolution

src/internal-context/load.ts, src/viewer.ts
=> chore: update resolveContentConfig a bit and viewer logging

docs/content/1.getting-started/1.installation.md
Updated the init commands because the other one doesn't work. Found this solution here: https://www.devgem.io/posts/why-npx-tailwindcss-init-fails-and-how-to-fix-it
Not that I could find.
I have updated the documentation for the init command. The current one online doesn't work, so I found a solution on https://www.devgem.io/posts/why-npx-tailwindcss-init-fails-and-how-to-fix-it
So I thought let's update this for everyone 👍
If my title is not correct, or if I need to change something, please let me know 😉
=> docs: mention `tailwindcss-cli` if `tailwindcss init` fails

src/internal-context/load.ts
#964 
Tailwindcss does not seem to work with content like this `pages/to/[...path].vue`. This change will replace those paths with a content like this `pages/to/?...path?.vue`. The question mark means any character. I tried many ways (like escaping the brackets) but they didn't seem to work.
I didn't write unit tests as the unit test system wasn't clear. Maybe if someone can give me an idea how to do this, I can write the tests.
=> fix: content resolution for [...path].vue pages

package.json, pnpm-lock.yaml
seems an unintended change in https://github.com/nuxt-modules/tailwindcss/pull/961
`@nuxt/kit` should be an explicit dependency as it is used in the source code of this module
=> chore: move kit back to explicit dependency

src/resolvers.ts
noticed this issue when multiple versions of tailwindcss were present in a monorepo. It's probably safest to resolve tailwind from the module itself given that it's a dependency of it (and pinned to `~3.4`)
=> fix: try resolving `tailwindcss` from module

src/module.ts
https://github.com/nuxt-modules/tailwindcss/issues/983
Check `isTailwind4` before logging the warning so it won't be shown when using v3.
=> fix: only show Tailwind v4 warning when v4 is used

docs/app/components/content/Sandbox.vue
Resolves #987 
The COOP blocks clicking on "Open in Stackblitz" on the pages.
=> fix(docs): add iframe sandbox property as else COOP errors occur
