nuxt-modules/tailwindcss

lib/module.js
=> feat: add support for deprecated build.postcss.plugins array syntax

lib/files/tailwind.config.js, lib/module.js, test/config.test.js, test/ok.test.js
Resolves https://github.com/nuxt-community/tailwindcss-module/issues/114
=> feat(purge): handle custom srcDir and support TS

docs/content/en/setup.md, docs/content/en/tailwind-config.md
=> docs: typo for Setup and tailwind config

lib/files/tailwind.css
Instead of using `@import`, apparently this should accelerate HMR.
=> feat: use @tailwind directive

lib/module.js, lib/ui/layouts/tw.vue, lib/ui/pages/index.vue
This feature will add a page in development on `/_tailwind`
=> feat: add tailwind colors page

lib/module.js
fix https://github.com/nuxt-community/tailwindcss-module/issues/224
=> fix: addTemplate call compats low version nuxt

docs/content/en/tailwind-config.md
=> docs: add whitelist section to purge

lib/module.js, lib/serverMiddleware/tailwindConfigViewer.js, package.json, yarn.lock
Hey! 👋 
According to [`ufo` changelog](https://github.com/nuxt-contrib/ufo/blob/main/CHANGELOG.md), nothing should be change to migrate the package.
Closes https://github.com/nuxt-community/tailwindcss-module/issues/265
=> chore: migrate @nuxt/ufo to ufo

example/tailwind.config.js, lib/module.js
Ref: https://github.com/nuxt/nuxt.js/issues/8971
=> fix: use nuxt resolver to import `tailwind.config.js`

docs/content/2.setup.md
Quick Setup - Match the readme.md
=> Update Setup Docs

docs/content/3.options.md, src/index.ts
=> feat: add css inject position

docs/content/tailwind/1.config.md
=> docs: update config.md

docs/content/tailwind/1.config.md
=> docs: Fix tailwind.config.ts url in docs

playground/nuxt.config.ts, src/module.ts
The tailwind viewer url is showing only "/_tailwind/" missing the rest of the url.
=> fix: tailwind viewer url

docs/content/tailwind/1.config.md
=> docs: fix typo

package.json
@Atinux, any chances to merge it soon? Are there any blockers? 🚀
Bumping the version to RC3 will remove the following error:
=> chore: upgrade to rc3

src/module.ts
=> fix: css intellisense not working

src/module.ts
fixes https://github.com/nuxt-modules/tailwindcss/issues/609
=> support nuxt 2.16+

README.md, docs/content/1.getting-started/2.options.md, test/fixture/basic/tsconfig.json
=> docs: broken links updated

src/module.ts
=> fix viewer endpoint route url

docs/content/1.getting-started/1.setup.md, package.json, pnpm-lock.yaml, src/module.ts
=> chore: remove @nuxt/postcss8

docs/content/1.getting-started/2.configuration.md
fix typo 
ref: https://tailwindcss.nuxtjs.org/getting-started/configuration#csspath
=> fix: docs typo injectionPosition -> injectPosition

docs/content/2.tailwind/3.editor-support.md
Provide more guidence to setup Tailwind  intelliSense in different editors.
=> docs: mention tailwind intelliSense integration with IDEs pointing to tailwind  docs  / editor config

docs/content/1.getting-started/1.installation.md
Resolves #911 
With `pnpm` as package manager, the command `pnpm dlx tailwindcss init` will create a `tailwind.config.js`, solving the user frustration with err `sh: 1: tailwind: not found`
=> docs: add proper command to create tailwind.config.js for pnpm
